// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxfYtrMc_--goMNkpU7AIW2bc31j_U5Uw',
    appId: '1:790063071837:android:447051752b7ee5c06d83b4',
    messagingSenderId: '790063071837',
    projectId: 'push-to-talk-c22fd',
    storageBucket: 'push-to-talk-c22fd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvD5hNrXg1GOMkVByG44t7sZ74tLXCE-w',
    appId: '1:790063071837:ios:a0a0fe9aa50ac7c66d83b4',
    messagingSenderId: '790063071837',
    projectId: 'push-to-talk-c22fd',
    storageBucket: 'push-to-talk-c22fd.firebasestorage.app',
    iosBundleId: 'com.example.pushToTalkApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnvL08DFbePtFshOMfzYKIHxOe-w0EfLk',
    appId: '1:790063071837:web:45ac4b38e48a4c916d83b4',
    messagingSenderId: '790063071837',
    projectId: 'push-to-talk-c22fd',
    authDomain: 'push-to-talk-c22fd.firebaseapp.com',
    storageBucket: 'push-to-talk-c22fd.firebasestorage.app',
    measurementId: 'G-69L49BFYNN',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvD5hNrXg1GOMkVByG44t7sZ74tLXCE-w',
    appId: '1:790063071837:ios:a0a0fe9aa50ac7c66d83b4',
    messagingSenderId: '790063071837',
    projectId: 'push-to-talk-c22fd',
    storageBucket: 'push-to-talk-c22fd.firebasestorage.app',
    iosBundleId: 'com.example.pushToTalkApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnvL08DFbePtFshOMfzYKIHxOe-w0EfLk',
    appId: '1:790063071837:web:2d78e616c89627926d83b4',
    messagingSenderId: '790063071837',
    projectId: 'push-to-talk-c22fd',
    authDomain: 'push-to-talk-c22fd.firebaseapp.com',
    storageBucket: 'push-to-talk-c22fd.firebasestorage.app',
    measurementId: 'G-TW8435CP0H',
  );

}